### PR TITLE
Milestone: JavaScript capstone project - Your API-based webapp

### PR DESCRIPTION
**Pull request by Kashif-Saleem-Ghuman**
### In this milestone:

- We have used built an API-based movie web app using HTML, CSS, JavaScript
- We fetch data from the  [TVmaze API](https://www.tvmaze.com/api) 
- We then display from that data 15 movies on our web page
- Further, we hit the [Involvement API](https://www.notion.so/microverse/Involvement-API-869e60b5ad104603aa6db59e08150270) to record the different user interactions i.e. likes, comments.
- Here is a video description of our project: https://drive.google.com/file/d/1UeOeRlV2ehm8cvYulInTwIxQttv3tkkJ/view?usp=sharing

### CODE REVIEW

**Review by TuyishimireEric — APPROVED** [review]
# Status: APPROVED 🟢  
### Hi  @Kashif-Saleem-Ghuman & @ohyajk   👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
done

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉 

## Highlights
✔️Equal Project contribution👍 
✔️professional README👍 
✔️professional PR👍 
✔️Project is working👍 
✔️No linter errors👍

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ohyajk** [comment]
Thank you @TuyishimireEric for your review.❤️🙏

**Comment by ohyajk** [comment]
I want to extend my regards to @Kashif-Saleem-Ghuman for working with me on this beautiful project together as a team. I believe that such understanding is scarce to have in groups. I am very much fortunate to be able to be paired with you. May god guide you and give you prosperity so you achieve your dreams.❤️🙏

**Comment by Kashif-Saleem-Ghuman** [comment]
Thankyou @TuyishimireEric  for reviewing our project 😄

**Comment by Kashif-Saleem-Ghuman** [comment]
Thankyou @ohyajk for the appreciation and kind words. 🙏

**Pull request merged**
